2020-11-25 05:06:26,409: DEBUG: NEW RUN: Client, TEST: Write_Multiple_Clients_Ten_Threads4
2020-11-25 05:06:26,409: DEBUG: The client is starting.
2020-11-25 05:06:26,409: DEBUG: The client is starting on port 37561
2020-11-25 05:06:26,410: DEBUG: Sent WRQ: b'\x00\x02/home/A365/tftp_threads/dist/read_files/thread_4.txt\x00netascii\x00'
2020-11-25 05:06:26,411: DEBUG: File exists, can send it
2020-11-25 05:06:26,412: DEBUG: First packet received. Raw bytes: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 05:06:26,412: DEBUG: New packet from: ('127.0.0.1', 41512), contents: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 05:06:26,412: DEBUG: Sending: /home/A365/tftp_threads/dist/read_files/thread_4.txt
2020-11-25 05:06:26,412: ERROR: Shutting down due to error packet. Error code: 2, error message: b'filename already exists at destination'
2020-11-25 05:06:26,412: WARNING: File didnt close on its own, closing now
2020-11-25 05:06:26,512: DEBUG: Client finished.
2020-11-25 05:06:26,512: DEBUG: Closing Socket
