2020-11-25 04:08:21,589: DEBUG: NEW RUN: Client, TEST: Write_Multiple_Clients_Ten_Threads9
2020-11-25 04:08:21,589: DEBUG: The client is starting.
2020-11-25 04:08:21,589: DEBUG: The client is starting on port 44978
2020-11-25 04:08:21,589: DEBUG: Sent WRQ: b'\x00\x02/home/A365/tftp_threads/dist/read_files/thread_9.txt\x00netascii\x00'
2020-11-25 04:08:21,591: DEBUG: File exists, can send it
2020-11-25 04:08:21,591: DEBUG: First packet received. Raw bytes: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:08:21,591: DEBUG: New packet from: ('127.0.0.1', 57670), contents: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:08:21,591: DEBUG: Sending: /home/A365/tftp_threads/dist/read_files/thread_9.txt
2020-11-25 04:08:21,592: ERROR: Shutting down due to error packet. Error code: 2, error message: b'filename already exists at destination'
2020-11-25 04:08:21,592: WARNING: File didnt close on its own, closing now
