2020-11-25 04:33:43,612: DEBUG: NEW RUN: Client, TEST: Write_Multiple_Clients_Twenty_Threads14
2020-11-25 04:33:43,612: DEBUG: The client is starting.
2020-11-25 04:33:43,612: DEBUG: The client is starting on port 9265
2020-11-25 04:33:43,612: DEBUG: Sent WRQ: b'\x00\x02/home/A365/tftp_threads/dist/read_files/thread_14.txt\x00netascii\x00'
2020-11-25 04:33:43,614: DEBUG: File exists, can send it
2020-11-25 04:33:43,614: DEBUG: First packet received. Raw bytes: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:33:43,614: DEBUG: Sending: /home/A365/tftp_threads/dist/read_files/thread_14.txt
2020-11-25 04:33:43,614: DEBUG: New packet from: ('127.0.0.1', 49365), contents: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:33:43,634: ERROR: Shutting down due to error packet. Error code: 2, error message: b'filename already exists at destination'
2020-11-25 04:33:43,634: WARNING: File didnt close on its own, closing now
2020-11-25 04:33:43,714: DEBUG: Client finished.
2020-11-25 04:33:43,715: DEBUG: Closing Socket
